"""empty message

Revision ID: 329a1d0786ac
Revises: 9552f7ef6465
Create Date: 2021-03-19 11:32:20.656618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '329a1d0786ac'
down_revision = '9552f7ef6465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('titles', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('imgs', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('descriptions', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###
