"""empty message

Revision ID: 6dc0f622f2c7
Revises: 
Create Date: 2021-03-23 14:52:12.241238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dc0f622f2c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favorites_user_id_fkey', 'favorites', type_='foreignkey')
    op.drop_constraint('favorites_project_id_fkey', 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'user_id')
    op.drop_column('favorites', 'project_id')
    op.drop_constraint('steps_project_id_fkey', 'steps', type_='foreignkey')
    op.create_foreign_key(None, 'steps', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'steps', type_='foreignkey')
    op.create_foreign_key('steps_project_id_fkey', 'steps', 'projects', ['project_id'], ['id'])
    op.add_column('favorites', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('favorites', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('favorites_project_id_fkey', 'favorites', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('favorites_user_id_fkey', 'favorites', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
